---

- hosts: os_MacOSX_10
  gather_facts: no
  tasks:
    - group_by:
        key: os_MacOSX_{{ '.'.join(ansible_facts.distribution_version.split('.')[0:2]) }}

- hosts: os_MacOSX_10.14
  gather_facts: no
  roles:
    - common
    - osx_defaults
    - homebrew
    - dotfiles
    - ghq
    - fish
