---

- name: OS、バージョン情報でグループ化
  hosts: all
  tasks:
    - group_by:
        key: os_{{ ansible_facts['distribution'] }}_{{ ansible_facts['distribution_major_version'] }}

- import_playbook: debian.yml
- import_playbook: macos.yml
