---

- name: Debianにdotfilesを展開
  hosts: debian9
  roles:
    - setup_git
    - setup_fzf
    - setup_vim
    - setup_less
    - setup_pyenv
    - setup_golang

    - setup_fish

    # - setup_rubyenv
    # - setup_nvm
