#!/bin/sh

chsh -s `which fish`

# git
rm ~/.gitignore_global
ln -s "`pwd`/home/.gitignore_global" ~/.gitignore_global

# fisherman
curl -Lo ~/.config/fish/functions/fisher.fish --create-dirs https://git.io/fisher

# nvm
fisher nvm

# git-foresta
sudo wget -O /usr/local/bin/git-foresta https://raw.githubusercontent.com/takaaki-kasai/git-foresta/master/git-foresta
sudo chmod +x /usr/local/bin/git-foresta
