---

- name: MacOSの設定を変更
  osx_defaults:
    domain: '{{ item.domain | default("NSGlobalDomain") }}'
    key: '{{ item.key | default("") }}'
    type: '{{ item.type | default("string") }}'
    value: '{{ item.value | default("") }}'
    array_add: '{{ item.array_add | default(False) }}'
  with_items: '{{ presented_osx_defaults }}'
  notify: サービスを再起動

- name: MacOSの設定を無効化
  osx_defaults:
    domain: '{{ item.domain | default("NSGlobalDomain") }}'
    key: '{{ item.key | default("") }}'
    state: absent
  with_items: '{{ absented_osx_defaults }}'
  notify: サービスを再起動
