---

- name: ghqのルートディレクトリを確認
  command: git config --global ghq.root
  changed_when: no
  ignore_errors: yes
  register: get_ghq_root_task

- name: ghqのルートディレクトリを変更
  command: 'git config --global ghq.root {{ ghq_root_path | regex_replace("^~", ansible_facts.user_dir) }}'
  when: get_ghq_root_task.stdout != (ghq_root_path | regex_replace("^~", ansible_facts.user_dir))
