---

homebrew_taps:
  - homebrew/cask-fonts
  - homebrew/core
homebrew_installed_packages:
  - ansible
  - coreutils
  - docker
  - fish
  - fzf
  - ghq
  - git
  - go
  - mas
  - pyenv
homebrew_uninstalled_packages: []
homebrew_upgrade_all_packages: no
homebrew_cask_apps:
  - 1password
  - alfred
  - apache-directory-studio
  - docker
  - bettertouchtool
  - font-ricty-diminished
  - google-chrome
  - hyperswitch
  - iterm2
  - karabiner-elements
  - keycast
  - kindle
  - spectacle
  - sublime-text
  - wireshark
homebrew_cask_uninstalled_apps: []

presented_osx_defaults:
  # 一般
  - { name: ダークモードを有効, key: AppleInterfaceStyle, type: string, value: Dark }
  # TODO: デフォルトのWebブラウザ
  # TODO: このMacとiCloudデバイス間でのHandoffを許可

  # デスクトップとスクリーンセーバー
  # TODO: 開始までの時間、開始しない

  # Dock
  - { name: Dockサイズを変更, domain: com.apple.dock, key: tilesize, type: float, value: 34 }
  - { name: 最近使ったアプリケーションをDockに表示しない, domain: com.apple.dock, key: show-recents, type: boolean, value: no }

  # Mission Control
  - { name: 最新の使用状況に基づいて操作スペースを自動的に並べ替えない, domain: com.apple.dock, key: mru-spaces, type: boolean, value: no }
  - { name: 'Dashboard オフ', domain: com.apple.dashboard, key: db-enabled-state, type: integer, value: 1 }

  # 言語と地域

  # セキュリティとプライバシー
  # TODO: スリープとスクリーンセーバの解除にパスワードを要求: すぐに
  # TODO: Apple WatchでこのMacをロック解除できるようにする

  # Spotlight

  # 通知

  # CDとDVD
  # TODO: 空のCDをセットしたときの動作: 動作を確認
  # TODO: 空のDVDをセットしたときの動作: 動作を確認
  # TODO: 音楽CDをセットしたときの動作: 無視
  # TODO: ピクチャCDをセットしたときの動作: 無視
  # TODO: ビデオDVDをセットしたときの動作: 無視

  # ディスプレイ

  # 省エネルギー
  # TODO: ディスプレイをオフにするまでの時間(バッテリー): しない
  # TODO: ディスプレイをオフにするまでの時間(電源アダプタ): しない
  # TODO: 可能な場合はハードディスクをスリープさせない(バッテリー)
  # TODO: 可能な場合はハードディスクをスリープさせない(電源アダプタ)
  - { name: 'メニューバーにバッテリーの状況を表示', domain: com.apple.systemuiserver, key: 'NSStatusItem Visible com.apple.menuextra.battery', type: boolean, value: true }
  - { name: '割合(%)を表示', domain: com.apple.menuextra.battery, key: ShowPercent, type: string, value: 'YES' }

  # キーボード
  - { name: キーのリピート設定, key: KeyRepeat, type: integer, value: 2 }
  - { name: リピート入力認識までの時間, key: InitialKeyRepeat, type: integer, value: 25 }
  - { name: 'F1、F2などのキーを標準のファンクションキーとして使用', key: com.apple.keyboard.fnState, type: boolean, value: yes }
  - { name: ライブ変換を無効, domain: com.apple.inputmethod.Kotoeri, key: JIMPrefLiveConversionKey, type: boolean, value: no }
  - { name: 英字入力中にスペルを自動変換しない, key: NSAutomaticSpellingCorrectionEnabled, type: boolean, value: no }
  - { name: 英字入力中にスペルを自動変換しない, key: WebAutomaticSpellingCorrectionEnabled, type: boolean, value: no }
  - { name: 文頭を自動的に大文字にしない, key: NSAutomaticCapitalizationEnabled, type: boolean, value: no }
  - { name: スペースバーを2回押してピリオドを入力しない, key: NSAutomaticPeriodSubstitutionEnabled, type: boolean, value: no }
  - { name: スマート引用符とスマートダッシュを使用しない, key: NSAutomaticDashSubstitutionEnabled, type: boolean, value: no }
  - { name: スマート引用符とスマートダッシュを使用しない, key: NSAutomaticQuoteSubstitutionEnabled, type: boolean, value: no }
  - { name: '"/"キーで入力する文字を"/(スラッシュ)"に設定', domain: com.apple.inputmethod.Kotoeri, key: JIMPrefCharacterForSlashKey, type: integer, value: 0 }
  - { name: '"¥"キーで入力する文字を"\(バックスラッシュ)"に設定', domain: com.apple.inputmethod.Kotoeri, key: JIMPrefCharacterForYenKey, type: integer, value: 1 }
  - { name: Tabキーを押して全てのコントロールを操作, key: AppleKeyboardUIMode, type: integer, value: 2 }
  # TODO: 修飾キー: Caps Lock

  # マウス

  # トラックパッド
  - { name: '調べる&データ検出(3本指でタップ)', domain: com.apple.AppleMultitouchTrackpad, key: TrackpadThreeFingerTapGesture, type: integer, value: 2 }
  - { name: '調べる&データ検出(3本指でタップ)', domain: com.apple.driver.AppleBluetoothMultitouch.trackpad, key: TrackpadThreeFingerTapGesture, type: integer, value: 2 }
  - { name: '副ボタンのクリック(2本指でクリックまたはタップ)', domain: com.apple.AppleMultitouchTrackpad, key: TrackpadRightClick, type: integer, value: 1 }
  - { name: '副ボタンのクリック(2本指でクリックまたはタップ)', domain: com.apple.driver.AppleBluetoothMultitouch.trackpad, key: TrackpadRightClick, type: integer, value: 1 }
  - { name: 'タップでクリック(1本指でクリック)', domain: com.apple.driver.AppleBluetoothMultitouch.trackpad, key: Clicking, type: boolean, value: yes }
  - { name: 'クリックの強さ(中)', domain: com.apple.AppleMultitouchTrackpad, key: FirstClickThreshold, type: integer, value: 1 }
  - { name: '軌跡の速さ', key: com.apple.trackpad.scaling, type: float, value: 0.8 }
  - { name: ページ間をスワイプ, key: AppleEnableSwipeNavigateWithScrolls, type: boolean, value: yes }
  - { name: 'フルスクリーンアプリケーション間をスワイプ(4本指で左右にスワイプ)', domain: com.apple.AppleMultitouchTrackpad, key: TrackpadFourFingerHorizSwipeGesture, type: integer, value: 2 }
  - { name: 'フルスクリーンアプリケーション間をスワイプ(4本指で左右にスワイプ)', domain: com.apple.driver.AppleBluetoothMultitouch.trackpad, key: TrackpadFourFingerHorizSwipeGesture, type: integer, value: 2 }
  - { name: 'Mission Control(4本指で上にスワイプ)', domain: com.apple.dock, key: showMissionControlGestureEnabled, type: boolean, value: yes }
  - { name: 'アプリケーションExpose(4本指で下にスワイプ)', domain: com.apple.dock, key: showAppExposeGestureEnabled, type: boolean, value: yes }

  # プリンタとスキャナ

  # サウンド
  - { name: 'メニューバーに音量を表示', domain: com.apple.systemuiserver, key: 'NSStatusItem Visible com.apple.menuextra.volume', type: boolean, value: true }

  # 起動ディスク

  # iCloud

  # インターネットアカウント

  # ソフトウェアアップデート

  # ネットワーク

  # Bluetooth
  - { name: 'メニューバーにBluetoothを表示', domain: com.apple.systemuiserver, key: 'NSStatusItem Visible com.apple.menuextra.bluetooth', type: boolean, value: true }
  - domain: com.apple.systemuiserver
    key: menuExtras
    type: array
    value:
      - "/System/Library/CoreServices/Menu Extras/AirPort.menu"
      - "/System/Library/CoreServices/Menu Extras/Battery.menu"
      - "/System/Library/CoreServices/Menu Extras/Bluetooth.menu"
      - "/System/Library/CoreServices/Menu Extras/Clock.menu"
      - "/System/Library/CoreServices/Menu Extras/Displays.menu"
      - "/System/Library/CoreServices/Menu Extras/Eject.menu"
      - "/System/Library/CoreServices/Menu Extras/TextInput.menu"
      - "/System/Library/CoreServices/Menu Extras/TimeMachine.menu"
      - "/System/Library/CoreServices/Menu Extras/User.menu"
      - "/System/Library/CoreServices/Menu Extras/Volume.menu"

  # 拡張機能

  # 共有

  # ユーザとグループ

  # ペアレンタルコントロール

  # Siri

  # 日付と時刻
  - { name: 'メニューバーに日付と時刻を表示', domain: com.apple.systemuiserver, key: 'NSStatusItem Visible com.apple.menuextra.clock', type: boolean, value: true }
  - { name: '秒を表示', domain: com.apple.menuextra.clock, key: DateFormat, type: string, value: 'M\\U6708d\\U65e5(EEE)  H:mm:ss' }

  # Time Machine

  # アクセシビリティ
  - { name: マウスポインタをシェイクして見つけるを無効化, key: CGDisableCursorLocationMagnification, type: boolean, value: yes }
  - { name: 透明度を下げる, domain: com.apple.universalaccess, key: reduceTransparency, type: boolean, value: yes }
  - { name: 'ドラッグを有効にする(3本指のドラッグ)', domain: com.apple.AppleMultitouchTrackpad, key: TrackpadThreeFingerDrag, type: boolean, value: yes }
  - { name: 'ドラッグを有効にする(3本指のドラッグ)', domain: com.apple.driver.AppleBluetoothMultitouch.trackpad, key: TrackpadThreeFingerDrag, type: boolean, value: yes }

  # プロファイル

  # Spectacle

absented_osx_defaults: []

mas_installed_apps:
  - { id: 402990477, name: 'PwGenerator (1.10.1)' }
  - { id: 409183694, name: 'Keynote (9.1)' }
  - { id: 461369673, name: 'VOX (3.3.10)' }
  - { id: 585829637, name: 'Todoist (7.1.3)' }
  - { id: 803453959, name: 'Slack (4.0.1)' }
mas_upgrade_all_apps: no
