---

- name: dotfilesリポジトリをclone
  block:
    - name: dotfilesリポジトリをsshで取得
      when: ansible_facts.env.SSH_CONNECTION is not match('^127\.0\.0\.1 \d+ 127\.0\.0\.1 \d+$')
      git:
        repo: '{{ dotfiles_git_repository }}'
        dest: '{{ dotfiles_clone_path }}'
        version: '{{ dotfiles_deploy_revision }}'
        force: yes
  rescue:
    - name: dotfilesリポジトリをhttpsで取得
      when: ansible_facts.env.SSH_CONNECTION is not match('^127\.0\.0\.1 \d+ 127\.0\.0\.1 \d+$')
      git:
        repo: '{{ dotfiles_https_repository }}'
        dest: '{{ dotfiles_clone_path }}'
        version: '{{ dotfiles_deploy_revision }}'
        force: yes
