---

- name: fzfリポジトリを取得
  become: yes
  git:
    repo: https://github.com/junegunn/fzf.git
    dest: /usr/local/lib/fzf
    force: yes
    version: master

- name: fzfをインストール
  become: yes
  shell: yes | ./install
  args:
    chdir: /usr/local/lib/fzf

- name: fzfを実行パスへリンク
  become: yes
  file:
    state: link
    src: /usr/local/lib/fzf/bin/fzf
    dest: /usr/local/bin/fzf
