alias lsl='ls -l'
alias lsa='ls -a'
alias lsal='ls -al'
alias lsla='ls -al'

alias gb='git branch'
alias gs='git status'
alias gd='git diff'
alias gco='git checkout'
alias gdc='git diff --cached'
alias grb='git rebase'
alias gst='git stash'
alias gcm='git commit'
alias ga='git add'
alias gmg='git merge'
alias gf='git fetch'
alias gp='git push'
