---

- name: vimをインストール
  become: yes
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
    cache_valid_time: 3000
  vars:
    packages:
      - vim

# vim設定ファイルの展開

- name: vim関連のディレクトリを作成
  file:
    state: directory
    path: "{{ item }}"
    recurse: yes
  with_items:
    - "{{ ansible_env.HOME }}/.config/vim"
    - "{{ ansible_env.HOME }}/.config/vim/filetype"

- name: vim設定ファイルを展開
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: "init.vim", dest: "{{ ansible_env.HOME }}/.config/vim/init.vim" }
    - { src: "dein.toml", dest: "{{ ansible_env.HOME }}/.config/vim/dein.toml" }
    - { src: "dein_lazy.toml", dest: "{{ ansible_env.HOME }}/.config/vim/dein_lazy.toml" }
    - { src: "filetype/", dest: "{{ ansible_env.HOME }}/.config/vim/filetype/" }

- name: vim関連ファイルのリンクを作成
  file:
    state: link
    force: yes
    path: "{{ ansible_env.HOME }}/{{ item.path }}"
    src: "{{ ansible_env.HOME }}/{{ item.src }}"
  with_items:
    - { src: ".config/vim/init.vim", path: ".vimrc" }
    - { src: ".config/vim/filetype", path: ".vim" }
