---

- name: ssh秘密鍵の存在確認
  find:
    paths: '{{ ansible_facts.user_dir }}/.ssh'
  register: get_ssh_keys_task

- name: ssh秘密鍵を生成
  command: ssh-keygen -t '{{ ssh_keygen_key_type }}' -P '{{ ssh_keygen_passphrase }}' -f {{ ansible_facts.user_dir }}/.ssh/id_{{ ssh_keygen_key_type }}
  when:
    - "(ansible_facts.user_dir + '/.ssh/id_ed25519') not in (get_ssh_keys_task.files | map(attribute='path') | list)"
    - "(ansible_facts.user_dir + '/.ssh/id_ed25519.pub') not in (get_ssh_keys_task.files | map(attribute='path') | list)"
