[[plugins]]
repo = 'terryma/vim-multiple-cursors'

[[plugins]]
repo = 'severin-lemaignan/vim-minimap'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]] # テーマ: TomorrowNight
repo = 'chriskempson/vim-tomorrow-theme'

[[plugins]] # ステータス出力を拡張
repo = 'itchyny/lightline.vim'

[[plugins]] # 空白文字をハイライト
repo = 'bronson/vim-trailing-whitespace'

[[plugins]] # 範囲コメントアウト
repo = 'tomtom/tcomment_vim'
